######################################################################
# Automatically generated by qmake (2.01a) ke 19. joulu 23:56:44 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h mandelbrot.h
SOURCES += dialog.cpp drawfunction.c main.cpp mandelbrot.cpp
